services:
  bot:
    container_name: maxhack-bot
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PROTOCOL: postgresql+psycopg
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: [ "python", "-OOm", "maxhack.bot" ]
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  scheduler:
    container_name: maxhack-scheduler
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PROTOCOL: postgresql+psycopg
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: [ "python", "-OOm", "maxhack.scheduler" ]
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    container_name: maxhack-migrations
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    env_file: .env
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PROTOCOL: postgresql+psycopg
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      database:
        condition: service_healthy

  api:
    container_name: maxhack-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file: .env
    environment:
      API_HOST: 0.0.0.0
      DB_HOST: database
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_PROTOCOL: postgresql+psycopg
    ports:
      - ${API_PORT}:${API_PORT}
    command: [ "python", "-OOm", "maxhack.web" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${API_PORT}/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  frontend:
    container_name: maxhack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      api:
        condition: service_healthy
      bot:
        condition: service_started

  database:
    container_name: maxhack-db
    image: postgres:16.9-alpine3.22
    restart: unless-stopped
    volumes:
      - maxhack-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 15s
      timeout: 4s
      retries: 3
      start_period: 3s

  redis: # TODO: запись на диск раз в N минут чтобы сберечь отложенные таски
    container_name: maxhack-redis
    image: redis:7.4.3-alpine3.21
    restart: unless-stopped
    command: "redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning --save 60 1"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  maxhack-volume:
