services:
  bot:
    container_name: maxhack-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    command: [ "python", "-OOm", "maxhack.bot" ]
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  scheduler:
    container_name: maxhack-scheduler
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    command: [ "python", "-OOm", "maxhack.scheduler" ]
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  broker:
    container_name: maxhack-broker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    command: [ "python", "-OOm", "maxhack.broker" ]
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    container_name: maxhack-migrations
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    env_file: .env
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      database:
        condition: service_healthy

  api: &main
    restart: "no"
    build:
      context: .

    ports:
      - ${PORT}:${PORT}

    env_file:
      - ./.env

    entrypoint: [ "python", "-OOm", "maxhack.web" ]

    volumes:
#      - ${FILES_PATH_VOLUME}:/var/project/app/storage
      - ./maxhack:/maxhack

    environment:
      - HOST=0.0.0.0
      - FILE_DIRECTORY=/var/project/app/storage
      # если вы используете свои postgres/redis/centrifugo то вам нужно закомментировать эти переменные
      - DB_HOST=database
      - DB_PORT=5432

  database:
    container_name: maxhack-db
    image: postgres:16.9-alpine3.22
    restart: unless-stopped
    volumes:
      - maxhack-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 15s
      timeout: 4s
      retries: 3
      start_period: 3s

  redis: # TODO: запись на диск раз в N минут чтобы сберечь отложенные таски
    container_name: maxhack-redis
    image: redis:7.4.3-alpine3.21
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: "redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning --save 60 1"

volumes:
  maxhack-volume:
